---
branches:
  only:
  - source
language: ruby
rvm:
- 1.9.3
before_script:
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- bundle execrake setup_github_pages[$REPO_URL]
script:
- bundle execrake generate
after_script:
- bundle execrake deploy
env:
  global:
  - GH_REPO="joluet/joluet.github.io"
  - secure: "vKuUEXwZ4aBW46HLAacpK0H/wVVDJZcT600qv8U+xVUrg3Fh258psIcBzWb0vqt89e+IOlcrISFNczNJHSUTGpjv6tYKqN0dMWKuUG0FP9P7IXGbJb9SiziqA7jEedegrnn1bbuwxXgYbn/mI4N/KfqLmS+TLFZ90fMDByA9fq0="

