---
branches:
  only:
  - source
language: ruby
rvm:
- 1.9.3
before_script:
  git config --global credential.helper "store --file=~/.git-credentials"
  echo "https://$GH_TOKEN:@github.com" > ~/.git-credentials
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- git config --global user.email "jonas@luethke.net"
- git config --global user.name "joluet"
- bundle exec rake setup_github_pages[$REPO_URL]
script:
- bundle exec rake generate
after_script:
- bundle exec rake deploy
env:
  global:
  - GH_REPO="joluet/joluet.github.io"
  - secure: "vKuUEXwZ4aBW46HLAacpK0H/wVVDJZcT600qv8U+xVUrg3Fh258psIcBzWb0vqt89e+IOlcrISFNczNJHSUTGpjv6tYKqN0dMWKuUG0FP9P7IXGbJb9SiziqA7jEedegrnn1bbuwxXgYbn/mI4N/KfqLmS+TLFZ90fMDByA9fq0="

